install.package("sodium")
install.package("shinyauthr")
install.package("devtools")
install.package("shinymanager")
install.package("shiny")
install.package("DT")
install.packagey("leaflet")
install.package("dplyr")
install.package("fontawesome")
install.package("shinydashboard")
install.package("shinycssloaders")
install.package("igraph")
install.package("markdown")
install.package("rmarkdown")
install.package("dplyr")
install.package("ggplot2")
install.package("visNetwork")
install.package("heatmaply")
install.package("plotly")
install.package("brew")
install.package("RColorBrewer")
install.package("curl")
install.package("wesanderson")

if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")

BiocManager::install("biomaRt")
